CREATE TABLE public.clientes (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre text NOT NULL, correo text NOT NULL UNIQUE, region text NOT NULL
);
CREATE TABLE public.productos (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre text NOT NULL, precio numeric(12,2) NOT NULL CHECK (precio>=0)
);
CREATE TABLE public.ventas (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cliente_id integer NOT NULL REFERENCES public.clientes(id),
 producto_id integer NOT NULL REFERENCES public.productos(id),
 cantidad integer NOT NULL CHECK (cantidad>0),
 fecha timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.empleados (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre text NOT NULL, cargo text NOT NULL, sueldo numeric(12,2) NOT NULL CHECK (sueldo>=0)
);
INSERT INTO public.clientes(nombre,correo,region) VALUES
 ('Ana Pérez','ana@example.test','Biobío'),('Carlos Díaz','carlos@example.test','Araucanía'),
 ('María Soto','maria@example.test','Ñuble'),('Diego Vera','diego@example.test','Biobío');
INSERT INTO public.productos(nombre,precio) VALUES
 ('Notebook',650000),('Monitor',150000),('Teclado',35000),('Mouse',18000);
INSERT INTO public.ventas(cliente_id,producto_id,cantidad) VALUES
 (1,1,1),(2,2,2),(3,3,3),(4,4,2),(1,2,1);
INSERT INTO public.empleados(nombre,cargo,sueldo) VALUES
 ('Andrea Ruiz','DBA',1800000),('Pablo Mora','Analista',1200000),('Camila Torres','Soporte',950000);
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
